/** Intentional concise list summaries for the registered visible command tree. */

export const COMMAND_SUMMARIES: Readonly<Record<string, string>> = {
  "check": "Run standalone repository checks",
  "check commit-msg": "Validate a commit message",
  "init": "Initialize ARC in the current project",
  "join": "Join an existing ARC project",
  "wu": "Manage the current work unit",
  "wu reconcile": "Plan or apply work-unit repairs",
  "start": "Start work in an isolated worktree",
  "stub": "Create a backlog work-unit stub",
  "decompose": "Manage a work-unit decomposition",
  "rename": "Rename a work unit and its identities",
  "promote": "Promote a provisional stub to planned",
  "demote": "Demote a planned stub to provisional",
  "park": "Park a started work unit",
  "resume": "Resume a parked work unit",
  "materialize": "Check out a remote-only work unit",
  "activate": "Activate a planning work unit",
  "deactivate": "Return an active work unit to planning",
  "publish": "Schedule work-unit publication",
  "integrate": "Check readiness and merge work units",
  "integrate checkpoint": "Assess integration readiness",
  "integrate merge": "Merge an approved integration checkpoint",
  "reopen": "Return an integrating work unit to active",
  "abandon": "Destroy a pre-merge work unit",
  "archive": "Archive a shipped work unit",
  "teardown": "Clean up a retired work unit",
  "set-stage": "Set the current planning stage",
  "finalize": "Record planning ceremony completion facts",
  "attest": "Attest a verified work-unit Candidate",
  "candidate": "Manage Candidate lineage transitions",
  "candidate applicability": "Classify and bind Candidate applicability",
  "candidate applicability resolve": "Resolve and bind Candidate applicability",
  "repoint-design": "Advance the current design pointer",
  "errand": "Manage Errand lifecycles",
  "errand next": "Find the next inbox Errand without opening it",
  "errand check": "Report work units touching target paths",
  "errand open": "Open an Errand in an available worktree",
  "errand link": "Link an Errand to its inbox capture",
  "errand leave": "Preserve an Errand and release its checkout",
  "errand materialize": "Check out a remote-only Errand generation",
  "errand merge": "Merge an approved Errand target",
  "errand close": "Complete an Errand and remove its inbox capture",
  "errand abandon": "Abandon a preserved Errand",
  "errand promote": "Promote an Errand to a work unit",
  "housekeep": "Prepare to drain the user inbox",
  "housekeep check": "Check the inbox-drain write context",
  "base": "Manage the local integration base",
  "base drift": "Analyze drift from the fetched integration base",
  "base merge": "Merge a checkpointed base revision",
  "base sync": "Fast-forward the local integration base",
  "plan": "Check where planning can begin",
  "plan check": "Resolve the planning-entry route",
  "delivery": "Author and manage delivery plans",
  "delivery authoring": "Resolve delivery authoring locations",
  "delivery authoring locate": "Locate candidate refs and detached gate paths",
  "delivery authoring rematerialize": "Prepare a private candidate ref and gate pair",
  "delivery authoring rebind": "Bind a detached authoring head to its candidate",
  "delivery closeout": "Clean up completed delivery records",
  "delivery entry inspect": "Inspect delivery intent and bindings",
  "delivery entry": "Inspect the delivery entry route",
  "delivery checks observe": "Observe required checks for a member head",
  "delivery checks": "Observe delivery-member required checks",
  "delivery eligibility": "Validate a delivery candidate chain",
  "delivery eligibility prepare": "Pin and validate the candidate chain",
  "delivery eligibility close": "Close the eligibility observation window",
  "delivery publish": "Publish member refs and open change requests",
  "delivery native": "Manage host-native stack presentation",
  "delivery native observe": "Observe native stack registration",
  "delivery native link": "Register a materialized native stack",
  "delivery native unlink": "Remove native stack presentation",
  "delivery native land-select": "Select native or sequential landing",
  "delivery native land-prepare": "Validate and reserve a native landing set",
  "delivery native land-submit": "Submit an authorized native landing",
  "delivery native land-status": "Poll and reconcile native landing status",
  "delivery native land-release": "Decline a settled landing and release its reservation",
  "delivery refresh": "Plan or adopt a provider-refreshed suffix",
  "delivery refresh plan": "Plan a registered suffix refresh",
  "delivery refresh execute": "Prepare and publish a native suffix refresh",
  "delivery refresh adopt": "Verify and adopt an external suffix refresh",
  "delivery review-fix": "Route and publish a member review fix",
  "delivery review-fix continue": "Resume a review-fix continuation",
  "delivery review-fix plan": "Select the review-fix publication route",
  "delivery review-fix publish": "Publish a selected member review fix",
  "delivery review-fix acknowledge": "Consume completed review-fix verification",
  "delivery position": "Determine the current delivery position",
  "delivery land": "Prepare and apply a member landing",
  "delivery land prepare": "Prepare a member landing presentation",
  "delivery land apply": "Apply an authorized member landing",
  "delivery reconcile": "Reconcile a persisted delivery operation",
  "delivery rewrite": "Rewrite a reviewed suffix member",
  "delivery rematerialize": "Reclose and rewrite a reviewed suffix",
  "delivery teardown": "Retire a landed member ref",
  "delivery top-remedy": "Apply a selected terminal request remedy",
  "delivery compose": "Validate an authoring map and publish its plan",
  "delivery plan": "Create or abandon delivery authoring state",
  "delivery plan inventory": "Inspect design-inventory authoring contracts",
  "delivery plan inventory schema": "Emit the design-inventory input schema",
  "delivery plan from-tasks": "Create an authoring map from active tasks",
  "delivery plan from-branch": "Create an authoring map from a branch",
  "delivery plan abandon": "Delete the outstanding authoring map",
  "delivery transfer": "Transfer delivery records between clones",
  "delivery transfer export": "Export the active work unit's delivery records",
  "delivery transfer import": "Import the active work unit's delivery records",
  "update": "Update installed ARC framework files",
  "health": "Show installed framework health",
  "diff": "Compare installed and latest framework files",
  "user": "Manage user directories and portable notes",
  "user add": "Create a team member's user directory",
  "user open": "Open a work-unit user workspace",
  "user close": "Remove a work-unit user workspace",
  "user inbox-mark-execute-bound": "Mark and order execute-bound inbox entries",
  "user inbox-remove": "Remove a title-matched inbox entry",
  "user save": "Save the user directory to Git notes",
  "user load": "Restore the user directory from Git notes",
  "user push": "Push user notes to the remote",
  "user fetch": "Fetch user notes from the remote",
  "user pull": "Fetch and restore user notes",
  "user compact": "Compact user notes history",
  "user status": "Inspect user notes and directory sync state",
  "user reconcile-references": "Inspect or repair managed user references",
  "user sync": "Synchronize user notes by direction",
  "extensions": "Inspect ARC extensions",
  "extensions status": "Show extension state and orphaned references",
  "schema": "Discover registered ARC contracts",
  "schema list": "List registered contract identities and metadata",
  "schema get": "Emit one registered contract as JSON",
  "config": "Inspect ARC configuration",
  "config status": "Show ARC configuration settings",
  "config validate": "Validate ARC configuration settings",
  "active": "Inspect active ARC work",
  "active status": "List in-flight work-unit status fields",
  "active roster": "List work units across worktrees",
  "active in-flight": "List in-flight work units and Errands",
  "view": "Display a work artifact",
  "status": "Inspect work, project, and session state",
  "locus": "Inspect checkout and session locations",
  "recover": "Support recovery after harness compaction",
  "recover audit": "Audit the latest compaction seed",
  "sync": "Synchronize configured worktree and user-note concerns",
  "release": "Validate and audit release operations",
  "release commit": "Commit with release-mode validation",
  "release push": "Push with release-mode validation",
  "release opt-in": "Enable release wrappers for this developer",
  "release opt-out": "Disable release wrappers for this developer",
  "release status": "Show release opt-in and interlock state",
  "release setup": "Manage release-wrapper harness integration",
  "release setup install": "Install release-wrapper harness integration",
  "release setup print-patterns": "Print harness allowlist patterns",
  "release setup uninstall": "Remove release-wrapper harness integration",
  "release setup verify": "Report recorded harness setup posture",
  "log": "Browse ARC commit history",
  "log standalone": "Show standalone commits outside work units",
  "merge": "Manage merge controls",
  "merge lock": "Resolve and change the host merge lock",
  "merge lock resolve": "Resolve how a pull request should open",
  "merge lock hold": "Lock a pull request at its exact head",
  "merge lock release": "Unlock a pull request at its exact head",
  "review": "Resolve and execute review workflows",
  "review change-request resolve": "Resolve change-request disposition for a head",
  "review change-request": "Manage change requests for exact heads",
  "review status": "Resolve target review, check, and base status",
  "review terminus accept": "Accept a delivery-member Owner terminus",
  "review terminus": "Manage explicit review termini",
  "review merge-method resolve": "Validate the configured merge method",
  "review merge-method": "Manage the configured merge method",
  "review checks await": "Await required checks for a pull-request head",
  "review checks": "Manage required status checks",
  "review readiness": "Validate lifecycle readiness for a head",
  "review planning-lane": "Classify a Git change for planning clearance",
  "review planning-grooming resolve": "Resolve a planning-grooming review exemption",
  "review planning-grooming": "Resolve planning-grooming review applicability",
  "review resolve": "Resolve the next review-policy action",
  "review frontline": "Manage frontline pre-publication reviews",
  "review frontline resolve": "Resolve change-set facts and review intent",
  "review frontline run": "Run a frontline review for an exact target",
  "review hosted": "Manage hosted pull-request reviews",
  "review hosted request": "Request a hosted pull-request review",
  "review hosted await": "Await a requested hosted review",
  "review hosted settle": "Reply to and resolve a hosted finding",
  "review changeset resolve": "Resolve a target's changeset-size recommendation",
  "review changeset": "Assess changeset size for review",
  "review local": "Manage immutable-source local reviews",
  "review local prepare": "Prepare an immutable local review",
  "review local attest": "Attest a normalized local review result",
  "review local resume": "Resume a durable local review",
  "review respond": "Manage a source-bound review response",
  "review reduce": "Reduce a durable review operation",
  "review pre-publication": "Resolve a work unit's pre-publication review procedure"
};
