/** Public commit-message validation contracts. */

export type {
  CommitCheckArtifactFamily,
  CommitCheckArtifactReference,
  CommitCheckArtifactResolution,
  CommitCheckArtifactResolver,
  CommitCheckConfiguration,
  CommitCheckConfigurationKey,
  CommitCheckConfigurationLocation,
  CommitCheckDetailValue,
  CommitCheckExemptionReason,
  CommitCheckFinding,
  CommitCheckFindingCode,
  CommitCheckFindingDetail,
  CommitCheckLocation,
  CommitCheckMessageLineLocation,
  CommitCheckOutcome,
  CommitCheckPolicy,
  CommitCheckRepositoryState,
  CommitCheckRole,
  CommitCheckSeverity,
  CommitCheckSkippedOutcome,
  CommitCheckValidatedOutcome,
  CommitCheckVerdict,
  CommitCheckWholeMessageLocation,
  CommitMessageFormat,
  ContextFooterMode,
} from "./types.js";
